/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#494454",
        "primary": "#d0bcff",
        "on-tertiary-fixed-variant": "#474646",
        "on-tertiary-fixed": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#929090",
        "secondary-container": "#454747",
        "on-surface-variant": "#cbc3d7",
        "on-tertiary-container": "#2a2a29",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#d0bcff",
        "secondary": "#c6c6c7",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-fixed-variant": "#454747",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "secondary-fixed": "#e2e2e2",
        "on-error": "#690005",
        "on-tertiary": "#313030",
        "surface": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed": "#1a1c1c",
        "surface-dim": "#131313",
        "on-secondary-container": "#b4b5b5",
        "surface-variant": "#353534",
        "background": "#131313",
        "on-primary-fixed-variant": "#5516be",
        "surface-tint": "#d0bcff",
        "on-primary-container": "#340080",
        "outline": "#958ea0",
        "on-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "on-primary-fixed": "#23005c",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "tertiary": "#c9c6c5",
        "tertiary-fixed-dim": "#c9c6c5",
        "surface-container": "#201f1f",
        "inverse-primary": "#6d3bd7",
        "on-primary": "#3c0091",
        "primary-container": "#a078ff",
        "primary-fixed": "#e9ddff",
        "on-secondary": "#2f3131",
        "on-background": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "unit": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px",
        "gutter-desktop": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
